variables:
  IMAGE_NAME: "$HARBOR_URL/t527/akdb/egov/bsp/demos/buildpacks-demo"
  DOCKER_HOST: tcp://dockerdaemon:2375
  DOCKER_TLS_CERTDIR: ""
  CNCF_BUILDER_IMAGE: "$HARBOR_URL/t527/akdb/egov/bsp/demos/paketobuildpacks/builder:base"
  DOCKER_IN_DOCKER_IMAGE: "$HARBOR_URL/hub.docker.com/library/docker:20.10.16-dind"
  DOCKER_IMAGE: "$HARBOR_URL/hub.docker.com/library/docker:20.10.16"

include:
  - local: create-java-maven-environment.yml
  - local: validation-jobs-build.yml
  - local: test-jobs-build.yml
  - local: image-build-push.yml

stages:
  - build
  - test
  - push
