variables:
  APP_IMAGE_NAME: "define me"
  CNCF_BUILDER_IMAGE: "paketobuildpacks/builder:tiny"
  DEBUG_BUILDPACK: "-log-level debug"
  # Any image with user "root" so that the cache can be deleted as "root".
  ANY_IMAGE_WITH_ROOTUSER: "docker:20.10.19"
  # Is needed for image based tests like e.g. with Testcontainers https://www.testcontainers.org
  DOCKER_IN_DOCKER_IMAGE: "docker:20.10.19-dind"

include:
  - local: create-java-maven-environment.yml
  - local: validation-jobs-build.yml
  - local: test-jobs-build.yml
  - local: image-build-push.yml
  - local: cleanup.yml

stages:
  - build
  - test
  - push
